apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-web-ingress
spec:
  tls:
  - hosts:
    - dec3mber.pp.ua
    secretName: my-web-certificate-7x669
  rules:
  - host: dec3mber.pp.ua
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-single-pod-service
            port:
              number: 80

